### ISSUE TITLE
Photon "could not communicate" issue

### ISSUE THREAD

**Issue by alisvkr** [spark/spark-setup-android#12] opened 2015-12-25 13:34 UTC
I'm trying to setup android SDK of photon to my app in android device. When ready button is pressed, sdk cannot find any photon device. I tried to connect access point of photon manually, this time i get "could not communicate wit Photon cloud. Make sure your Android device is connected to the internet and retry."
Same situation occurs original Particle android app. I am testing sdk and your app in Nexus 5 android version 6.0.1. Also, my app with integrated sdk and original Particle app are working properly in another phones which I tested. Some logs:
**12-25 15:15:32.240 27013-31361/com.machina.robogame D/Retrofit: java.net.UnknownHostException: Unable to resolve host "api.spark.io": No address associated with hostname
                                                                    at java.net.InetAddress.lookupHostByName(InetAddress.java:470)
                                                                    at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
                                                                    at java.net.InetAddress.getAllByName(InetAddress.java:215)
                                                                    at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
                                                                    at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:187)
                                                                    at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:156)
                                                                    at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:98)
                                                                    at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
                                                                    at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:327)
                                                                    at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
                                                                    at com.squareup.okhttp.Call.getResponse(Call.java:267)
                                                                    at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
                                                                    at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
                                                                    at com.squareup.okhttp.Call.execute(Call.java:79)
                                                                    at retrofit.client.OkClient.execute(OkClient.java:53)
                                                                    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
                                                                    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
                                                                    at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                                    at $Proxy0.generateClaimCode(Unknown Source)
                                                                    at io.particle.android.sdk.cloud.ParticleCloud.generateClaimCode(ParticleCloud.java:270)
                                                                    at io.particle.android.sdk.devicesetup.ui.GetReadyActivity$3.callApi(GetReadyActivity.java:118)
                                                                    at io.particle.android.sdk.devicesetup.ui.GetReadyActivity$3.callApi(GetReadyActivity.java:109)
                                                                    at io.particle.android.sdk.utils.Async$AsyncApiWorker.doInBackground(Async.java:103)
                                                                    at io.particle.android.sdk.utils.Async$AsyncApiWorker.doInBackground(Async.java:71)
                                                                    at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                    at java.lang.Thread.run(Thread.java:818)
                                                                 Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
                                                                    at libcore.io.Posix.android_getaddrinfo(Native Method)
                                                                    at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
                                                                    at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
                                                                    at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252) 
                                                                    at java.net.InetAddress.getAllByName(InetAddress.java:215) 
                                                                    at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29) 
                                                                    at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:187) 
                                                                    at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:156) 
                                                                    at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:98) 
                                                                    at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344) 
                                                                    at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:327) 
                                                                    at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245) 
                                                                    at com.squareup.okhttp.Call.getResponse(Call.java:267) 
                                                                    at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224) 
                                                                    at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195) 
                                                                    at com.squareup.okhttp.Call.execute(Call.java:79) 
                                                                    at retrofit.client.OkClient.execute(OkClient.java:53) 
                                                                    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326) 
                                                                    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) 
                                                                    at java.lang.reflect.Proxy.invoke(Proxy.java:393) 
                                                                    at $Proxy0.generateClaimCode(Unknown Source) 
                                                                    at io.particle.android.sdk.cloud.ParticleCloud.generateClaimCode(ParticleCloud.java:270) 
                                                                    at io.particle.android.sdk.devicesetup.ui.GetReadyActivity$3.callApi(GetReadyActivity.java:118) 
                                                                    at io.particle.android.sdk.devicesetup.ui.GetReadyActivity$3.callApi(GetReadyActivity.java:109) 
                                                                    at io.particle.android.sdk.utils.Async$AsyncApiWorker.doInBackground(Async.java:103) 
                                                                    at io.particle.android.sdk.utils.Async$AsyncApiWorker.doInBackground(Async.java:71) 
                                                                    at android.os.AsyncTask$2.call(AsyncTask.java:295) 
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                    at java.lang.Thread.run(Thread.java:818) 
12-25 15:15:32.240 27013-31361/com.machina.robogame D/Retrofit: ---- END ERROR
12-25 15:15:32.273 27013-27013/com.machina.robogame E/Async: Error calling API: Unable to connect to the server.
                                                             io.particle.android.sdk.cloud.ParticleCloudException
                                                                 at io.particle.android.sdk.cloud.ParticleCloud.generateClaimCode(ParticleCloud.java:272)
                                                                 at io.particle.android.sdk.devicesetup.ui.GetReadyActivity$3.callApi(GetReadyActivity.java:118)
                                                                 at io.particle.android.sdk.devicesetup.ui.GetReadyActivity$3.callApi(GetReadyActivity.java:109)
                                                                 at io.particle.android.sdk.utils.Async$AsyncApiWorker.doInBackground(Async.java:103)
                                                                 at io.particle.android.sdk.utils.Async$AsyncApiWorker.doInBackground(Async.java:71)
                                                                 at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                 at java.lang.Thread.run(Thread.java:818)
12-25 15:15:32.273 27013-27013/com.machina.robogame D/GetReadyActivity: Generating claim code failed**

**Comment by jensck** [comment] 2015-12-29 18:52
This is just a DNS resolution error, and is mostly likely caused by a temporary internet connection problem; DNS for `api.spark.io` is resolving fine from my laptop and mobile devices.

It's very unlikely that this has anything to do with the SDK specifically, so I'm going to close this.  That said, if you run into the issue again, and you have more info which might point to an SDK or Particle Cloud issue, please feel free to re-open this!

**Closed by jensck** 2015-12-29 18:52 UTC
